version: '3.8'

services:
  dbPostgres:
    container_name: busdb
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:  ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - interdb

  pgAdmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - '15432:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@busdb.com
      PGADMIN_DEFAULT_PASSWORD: busdb2023
    volumes:
      - busdb:/data/pgadmin
    networks:
      - interdb

networks:
  default:
    name: busdb_default
    driver: bridge

  interdb:
    name: busdb_interdb
    driver: bridge

volumes:
  busdb:
